"""Changed date to String

Revision ID: 00816161d4e5
Revises: c5b744ed4022
Create Date: 2025-01-22 20:05:55.377206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00816161d4e5'
down_revision = 'c5b744ed4022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
