"""Initial MIgration

Revision ID: c5b744ed4022
Revises: 
Create Date: 2025-01-22 19:56:08.663810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b744ed4022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('contentparagraph1', sa.String(), nullable=True),
    sa.Column('contentparagraph2', sa.String(), nullable=True),
    sa.Column('contentparagraph3', sa.String(), nullable=True),
    sa.Column('contentparagraph4', sa.String(), nullable=True),
    sa.Column('contentparagraph5', sa.String(), nullable=True),
    sa.Column('contentparagraph6', sa.String(), nullable=True),
    sa.Column('contentparagraph7', sa.String(), nullable=True),
    sa.Column('contentparagraph8', sa.String(), nullable=True),
    sa.Column('contentparagraph9', sa.String(), nullable=True),
    sa.Column('contentparagraph10', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stories')
    # ### end Alembic commands ###
